version: '3.9'
name: web_verify
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "4001:80"
    volumes:
      - web_data_verify:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      web_clinic_verify:
        ipv4_address: 192.168.41.2

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      web_clinic_verify:
        ipv4_address: 192.168.41.3


networks:
  web_clinic_verify:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.41.0/24

volumes:
  web_data_verify:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
